[GD-52] Add trasactions interface
mirage-xyz/mirage-unity-sdk pull request #18
Opened 2022-03-07 12:40 UTC by sidorovkirill

2022-03-07 12:53 UTC, Vukiz commented on Assets/MirageSDK/Examples/Scripts/ERC20Example/ERC20Example.cs
> +			var trx = await _mirageSdk.Eth().GetTransaction(receipt);
do not cache IMirageSDK and cache Eth instance instead. you don't use anything from IMirageSDK after initialization

2022-03-07 13:13 UTC, Vukiz requested changes

2022-03-07 13:13 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Implementation/Eth.cs
> +	public class CommonProvider : ICommonProvider
file name is Eth while classname is different. User refactor->rename to avoid such situations.

2022-03-07 13:13 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Infrastructure/ICommonProvider.cs
> +	public interface ICommonProvider : ISignatureProvider, ITransactionProvider
ISignatureProvider is not needed here as it is already implemented by ITransactionProvider

2022-03-07 13:13 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Implementation/Eth.cs
> +		public CommonProvider(IWeb3 web3Provider)
Can we just get rid of all the interfaces(as static interfaces are not supported yet) and make this class static.
Let's remove constructor which requires us to provide IWeb3 and just pass it into methods where it is needed?

2022-03-07 13:13 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Implementation/Eth.cs
> +
```suggestion
```

2022-03-09 06:51 UTC, sidorovkirill commented on Assets/MirageSDK/Scripts/Core/Infrastructure/IMirageSDK.cs
> +		ICommonProvider Eth();
Then we will have totally new naming that can't be match with web3

2022-03-09 06:57 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Infrastructure/IMirageSDK.cs
> +		ICommonProvider Eth();
And I don't see this as a problem - if we are providing a full functionality support it does not matter how we name it.
You can make it a get only property if you want to keep a name.

2022-03-09 06:58 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Infrastructure/IMirageSDK.cs
> +using MirageSDK.Core.Implementation;
unused using

2022-03-09 10:44 UTC, sidorovkirill commented on Assets/MirageSDK/Scripts/Core/Infrastructure/ITransactionProvider.cs
> +	public interface ITransactionProvider : ISignatureProvider
Part

2022-03-11 06:14 UTC, Vukiz approved these changes

2022-03-11 06:18 UTC, merged