[GD-20] Add filters to events receiver
mirage-xyz/mirage-unity-sdk pull request #3
Opened 2022-02-03 08:24 UTC by sidorovkirill

2022-02-03 08:27 UTC, Krayt78 approved these changes

2022-02-03 11:29 UTC, Vukiz requested changes

2022-02-03 11:29 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Implementation/Contract.cs
> +        public BlockParameter fromBlock;
Can you please fix identation here?

2022-02-03 11:29 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Implementation/Contract.cs
> +			var isBockNumbersExisted = evFilter.fromBlock != null || evFilter.toBlock != null;
isBlockNumberExists

2022-02-03 11:29 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Implementation/Contract.cs
> +		public Task<List<EventLog<TEvDto>>> GetAllChanges<TEvDto>(EventFilterData evFilter) where TEvDto : IEventDTO, new()
We should make evFilter parameter optional and let user get all changes with no filter.

2022-02-03 11:29 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Implementation/Contract.cs
> +			NewFilterInput filters = eventHandler.CreateFilterInput();
user "var" where type is unnecessary or clear from right side of expression

2022-02-03 11:29 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Implementation/Contract.cs
> +			if (isBockNumbersExisted) {
```suggestion
			if (isBockNumbersExisted) 
			{
```

2022-02-03 11:29 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Implementation/Contract.cs
> +		public Task<List<EventLog<TEvDto>>> GetAllChanges<TEvDto>(EventFilterData evFilter) where TEvDto : IEventDTO, new()
Also without default implementation it will break ERC721Example:GetEvents()

2022-02-03 11:29 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Implementation/Contract.cs
> +			}
Extract this to another method so our code remains clean and readable

2022-02-04 05:46 UTC, sidorovkirill commented on Assets/MirageSDK/Scripts/Core/Implementation/Contract.cs
> +			NewFilterInput filters = eventHandler.CreateFilterInput();
Is it good practice?

2022-02-04 06:23 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Implementation/Contract.cs
> +			NewFilterInput filters = eventHandler.CreateFilterInput();
It is a C# naming convention. If you are able to understand type of this expression by right side or you don't need to know type - you don't need to specify it on the left.

2022-02-04 07:17 UTC, sidorovkirill commented on Assets/MirageSDK/Scripts/Core/Implementation/Contract.cs
> +			var isBockNumbersExisted = evFilter.fromBlock != null || evFilter.toBlock != null;
I changed condition

2022-02-04 07:33 UTC, Vukiz requested changes

2022-02-04 07:33 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Examples/ERC721Example.cs
> +			var events = await _erc721Contract.GetAllChanges<TransferEventDTO>(null);
you don't need to pass null if default value is null

2022-02-04 07:33 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Infrastructure/IContract.cs
> +		Task<List<EventLog<TEvDto>>> GetAllChanges<TEvDto>(EventFilterData evFilter) where TEvDto : IEventDTO, new();
you can make default value  = null here

2022-02-04 07:33 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Implementation/Contract.cs
> +				var isBockNumbersExisted = evFilter.fromBlock != null || evFilter.toBlock != null ||
fix naming please

2022-02-04 07:33 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Implementation/Contract.cs
> +				                           evFilter.fromBlock != null && evFilter.toBlock != null;
do you need to check if both of blocks are not null? I think first line is enough

2022-02-04 07:33 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Implementation/Contract.cs
> +			Event<TEvDto> eventHandler = _web3.Eth.GetEvent<TEvDto>(_address);
use var here

2022-02-04 07:33 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Implementation/Contract.cs
> +				if (isBockNumbersExisted)
you can move everything related to filterTopic inside these if block so you will not have to check if isBockNumbersExisted everytime

2022-02-04 08:16 UTC, Vukiz approved these changes

2022-02-04 08:18 UTC, merged