GD-01 Load NFTs
mirage-xyz/mirage-unity-sdk pull request #6
Opened 2022-02-17 10:09 UTC by Krayt78

2022-02-17 10:24 UTC, Vukiz requested changes

2022-02-17 10:24 UTC, Vukiz commented on Assets/MirageSDK/UseCases/LoadNFTs/LoadNFTExample.cs
> +
```suggestion
```

2022-02-17 10:24 UTC, Vukiz commented on Assets/MirageSDK/UseCases/LoadNFTs/LoadNFTExample.cs
> +        [SerializeField] private Text _text;
It is better to not use UnityEngine.UI.Text because it looks awful with just a slight changes. Stick to using TMP_Text

2022-02-17 10:24 UTC, Vukiz commented on Assets/MirageSDK/UseCases/LoadNFTs/LoadNFTExample.cs
> +            const string tokenOfOwnerByIndex = "tokenOfOwnerByIndex";
please move const, evene if it is local, to the top of this method

2022-02-17 10:24 UTC, Vukiz commented on Assets/MirageSDK/UseCases/LoadNFTs/LoadNFTExample.cs
> +
```suggestion
```
Please reformat your code before submission. It will automatically remove all unnecessary empty lines

2022-02-17 10:24 UTC, Vukiz commented on Assets/MirageSDK/UseCases/LoadNFTs/LoadNFTExample.cs
> +            Debug.Log($"Address owns this Token : {token}");
Seems like it will be a perfect fit to move 
`Debug.Log($"Address owns this Token : {token}");`
inside a `private void UpdateUILogs(string log)` method

2022-02-17 10:24 UTC, Vukiz commented on Assets/MirageSDK/UseCases/LoadNFTs/ReadMe.md
> +This is an example for one of the use cases for this sdk : Checking if someone owns an NFTs. This use case is usefull when you want to know if someone has specifix NFTs to then let him use it ingame.
```suggestion
This is an example for one of the use cases for this sdk : <br/>Checking if someone owns an NFTs. This use case is usefull when you want to know if someone has specific NFT's to then let him use it ingame. 
```

2022-02-17 10:24 UTC, Vukiz commented on Assets/MirageSDK/UseCases/LoadNFTs/ReadMe.md
> +To start this Use Case we will first need to initializethe SDKWrapper and store the contracts that we will use here inside some private variables. For this example i will reuse the GameCharacterContr
```suggestion
To start this Use Case we will first need to initialize the SDKWrapper and store the contracts that we will use here inside some private variables. For this example we will reuse the GameCharacterContract used in the WearableNFTExample Use Case.
```

2022-02-18 08:46 UTC, sidorovkirill commented on Assets/MirageSDK/UseCases/LoadNFTs/LoadNFTExample.cs
> +        private const string TransactionGasLimit = "1000000";
There is no need to clarify gasLimit it will be define automatically.

2022-02-21 06:03 UTC, Vukiz approved these changes

2022-02-21 06:51 UTC, merged