[GD-36] Send method
mirage-xyz/mirage-unity-sdk pull request #8
Opened 2022-02-18 06:29 UTC by sidorovkirill

2022-02-18 07:00 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Infrastructure/IContract.cs
> +		EventController SendMethod(string methodName, object[] arguments = null, string gas = null);
I don't like this naming it does not represent which one should I use this one or CallMethod

2022-02-18 07:01 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Implementation/Contract.cs
> +			{
As you are duplicating code here you should not repeat yourself, but rather extract this piece of code into a separate method. Also you are capturing evController into a closure which is better to be done explicitly

2022-02-18 07:02 UTC, Vukiz commented on Assets/MirageSDK/Examples/Scripts/ERC20Example/ERC20Example.cs
> +			promiEvent.OnReceipt += (s, _receipt) => Debug.Log("Receipt: " + _receipt.Status);
parameters are not named with "_"

2022-02-18 07:28 UTC, sidorovkirill commented on Assets/MirageSDK/Scripts/Core/Infrastructure/EventController.cs
> +			OnSending.Invoke(this, transaction);
What I should do if it is null?

2022-02-18 07:29 UTC, sidorovkirill commented on Assets/MirageSDK/Scripts/Core/Infrastructure/IContract.cs
> +		EventController SendMethod(string methodName, object[] arguments = null, string gas = null);
Actually it's literally web3 naming
<img width="776" alt="image" src="https://user-images.githubusercontent.com/38144180/154637615-6a90a06a-e604-4703-8214-a1ccabbb6a9e.png">

2022-02-21 06:12 UTC, Vukiz requested changes

2022-02-21 06:12 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Implementation/Contract.cs
> +			TransactionInput raw = _web3Provider.Eth.GetContract(_contractABI, _contractAddress)
Naming is incorrect and you should use var.

2022-02-21 06:12 UTC, Vukiz commented on Assets/MirageSDK/Scripts/Core/Implementation/Contract.cs
> +			var evController = new EventController();
I think it will be a lot better for users if we let them create and configure EventController : IEventController.
So our method will be 
`EventController Web3SendMethod(string methodName, object[] arguments = null, string gas = null, IEventController eventController = null)` 
this way use can pass all the callback he wants and we wont need any continuewith and will just simply work without legacy features.

2022-02-24 09:37 UTC, Vukiz approved these changes

2022-02-24 09:38 UTC, merged