Gd 43 fix wearable nft example
mirage-xyz/mirage-unity-sdk pull request #9
Opened 2022-02-21 14:28 UTC by Krayt78

2022-02-22 02:16 UTC, Vukiz requested changes

2022-02-22 02:16 UTC, Vukiz commented on Assets/MirageSDK/Examples/Scripts/WearableNFTExample/WearableNFTExample.cs
> +
Remove extra line

2022-02-22 02:16 UTC, Vukiz commented on Assets/MirageSDK/Examples/Scripts/WearableNFTExample/WearableNFTExample.cs
> +				new object[] {"0x510c522ebCC6Eb376839E0CFf5D57bb2F422EB8b", itemsToMint, itemsAmounts, new byte[] { }});
move hardcoded address to const

2022-02-22 02:16 UTC, Vukiz commented on Assets/MirageSDK/Examples/Scripts/WearableNFTExample/WearableNFTExample.cs
> +				new object[] {"0x510c522ebCC6Eb376839E0CFf5D57bb2F422EB8b", itemsToMint, itemsAmounts, new byte[] { }});
also extract `new byte[] {}` into local variable

2022-02-22 02:16 UTC, Vukiz commented on Assets/MirageSDK/Examples/Scripts/WearableNFTExample/WearableNFTExample.cs
> +		#region Button Calls
region should be indented one tab less

2022-02-22 07:41 UTC, Krayt78 commented on Assets/MirageSDK/Examples/Scripts/WearableNFTExample/WearableNFTExample.cs
> +		#region Button Calls
i might have to reconfigure my rider as i used the reformat code & cleanup before the pull request. 
Could you send me your rider config ?

2022-02-24 04:40 UTC, Vukiz approved these changes

2022-02-24 07:15 UTC, merged